# Generated by Django 3.0.4 on 2020-04-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_feedback', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
